version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo MONGO_URI=$MONGO_URI > .env
  build:
    commands:
      - echo Starting migrations...
      - npx migrate-mongo up
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then npx migrate-mongo down && exit 1; fi"
      - echo Migrated successfully completed on `date`
