export const TagsMapping = {
  rooms: [
    'bar',
    'bathroom',
    'bedroom',
    'cafe & restaurant',
    'dining room',
    'entrance',
    'gym/sport rooms',
    'hair',
    'hallway',
    'home office & office',
    'home office',
    'kids & nursery',
    'kids room',
    'kitchen & cafe',
    'kitchen & dining room',
    'kitchen',
    'laundry room',
    'living room',
    'lobby',
    'man cave & bar',
    'mancave',
    'nail salon',
    'nursery',
    'office',
    'restaurant',
    'salon',
    'spa',
    'teenager',
    'wall',
  ],
  styles: [
    'american',
    'casual',
    'commercial',
    'contemporary',
    'corporate',
    'cosy',
    'craftsman',
    'eclectic',
    'farmhouse',
    'feminine',
    'hipster',
    'masculine',
    'mature',
    'mediterranean',
    'minimalist',
    'modern',
    'nautical',
    'oriental',
    'rustic',
    'scandinavian',
    'shabby chic',
    'traditional',
    'transitional',
    'vintage',
    'wellness',
  ],
  colors: [
    'b&w',
    'black',
    'black/brown',
    'black/gray',
    'blue',
    'brown',
    'gray',
    'green',
    'light blue',
    'orange',
    'pink',
    'purple',
    'red',
    'vanilla',
    'yellow',
  ],
  unique: [
    'african',
    'bizarre',
    'bold color',
    'close zoom',
    'dark',
    'festive',
    'good',
    'greenery',
    'horizontal',
    'lights',
    'main zoom',
    'musical',
    'patio',
    'pets',
    'pop of color',
    'sporty',
    'vertical',
    'wide angle',
    'wide',
    'zoom',
  ],
};
